# Generated by Django 5.1.3 on 2024-11-23 08:59

import django.contrib.auth.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(verbose_name='Имя')),
                ('surname', models.TextField(verbose_name='Фамилия')),
                ('patronymic', models.TextField(verbose_name='Отчество')),
                ('biscenters', models.TextField(verbose_name='Бизнес-центр')),
                ('age', models.TextField(verbose_name='Возраст')),
                ('sex', models.BooleanField(verbose_name='Пол')),
                ('step_norm_day', models.IntegerField(verbose_name='Норма шагов в день')),
                ('procent_day', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Процент дня')),
                ('telegram_id', models.IntegerField(unique=True, verbose_name='Телеграм ID')),
                ('town', models.CharField(max_length=255, verbose_name='Город')),
                ('block', models.BooleanField(verbose_name='Блокировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперпользователь')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
