# Generated by Django 5.1.3 on 2024-11-23 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscenters', '0001_initial'),
        ('towns', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='biscenters',
        ),
        migrations.RemoveField(
            model_name='user',
            name='block',
        ),
        migrations.RemoveField(
            model_name='user',
            name='procent_day',
        ),
        migrations.AddField(
            model_name='user',
            name='biscenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='biscenters.biscenter', verbose_name='Бизнес-центр'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_block',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=2, max_length=255, unique=True, verbose_name='Логин'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('Муж', 'Муж'), ('Жен', 'Жен')], max_length=3, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Телеграм ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='towns.town', verbose_name='Город'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
