# Generated by Django 5.1.3 on 2024-11-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_biscenters_remove_user_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='access_token',
            field=models.TextField(null=True, verbose_name='access token'),
        ),
        migrations.AddField(
            model_name='user',
            name='code_verifier',
            field=models.TextField(null=True, verbose_name='Код Фитбита'),
        ),
        migrations.AddField(
            model_name='user',
            name='fitbit_user_id',
            field=models.TextField(null=True, verbose_name='ID пользователя Фитбит'),
        ),
        migrations.AddField(
            model_name='user',
            name='refresh_token',
            field=models.TextField(null=True, verbose_name='refresh token'),
        ),
    ]
