# Generated by Django 5.1.3 on 2024-11-23 16:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biscenters', '0001_initial'),
        ('indicators', '0001_initial'),
        ('telegram_chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала')),
                ('date_end', models.DateTimeField(verbose_name='Дата окончания')),
                ('goal', models.IntegerField(verbose_name='Цель')),
                ('points', models.IntegerField(verbose_name='Очки')),
                ('team', models.BooleanField(verbose_name='Командное событие')),
                ('biscenter', models.ManyToManyField(null=True, related_name='events', to='biscenters.biscenter', verbose_name='Бизнес-центр')),
                ('indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='indicators.indicator', verbose_name='Индикатор')),
                ('telegram_chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='telegram_chats.telegramchat', verbose_name='Чат в Telegram')),
            ],
            options={
                'verbose_name': 'Командная активность',
                'verbose_name_plural': 'Командные активности',
                'db_table': 'event',
            },
        ),
    ]
