# Generated by Django 5.1.3 on 2024-11-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='active',
            field=models.BooleanField(default=False, null=True, verbose_name='Событие активно'),
        ),
    ]
