# Generated by Django 5.1.3 on 2024-11-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biscenters', '0001_initial'),
        ('events', '0002_event_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='active',
            field=models.BooleanField(verbose_name='Событие активно'),
        ),
        migrations.AlterField(
            model_name='event',
            name='biscenter',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='biscenters.biscenter', verbose_name='Бизнес-центр'),
        ),
        migrations.AlterField(
            model_name='event',
            name='points',
            field=models.IntegerField(blank=True, null=True, verbose_name='Очки'),
        ),
    ]
