# Generated by Django 5.1.3 on 2024-11-23 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_active_alter_event_biscenter_and_more'),
        ('telegram_chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='points',
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Наименование активности'),
        ),
        migrations.AlterField(
            model_name='event',
            name='telegram_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='telegram_chats.telegramchat', verbose_name='Чат в Telegram'),
        ),
    ]
