services:
  backend:
    build:
      context: .
    ports:
      - 8000:8000/tcp
    volumes:
      - .:/app:rw
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    networks:
      - default
    depends_on:
      - database
  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    expose:
      - 5432
    ports:
      - 5432:5432/tcp

networks:
  default:
    driver: bridge
