services:

  backend:
    build:
      context: .
    ports:
      - 8000:8000/tcp
    volumes:
      - .:/app:rw
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    networks:
      - default
    depends_on:
      - database

  database:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    expose:
      - 5432
    ports:
      - 5432:5432/tcp

  redis:
    container_name: redis
    hostname: redis
    image: redis:7.2-rc-alpine3.18

  worker:
    container_name: worker
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - .:/app:rw
    links:
      - redis
    depends_on:
      - redis
      - database

  celerybeat:
    container_name: worker_beat
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app beat --loglevel=info
    volumes:
      - .:/app:rw
    links:
      - redis
    depends_on:
      - redis
      - database

  flower:
    container_name: flower
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - .:/app:rw
    links:
      - redis
    depends_on:
      - redis
    ports:
      - 5555:5555

networks:
  default:
    driver: bridge
