# Generated by Django 5.1.3 on 2024-11-23 16:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram_chats', '0001_initial'),
        ('towns', '0001_initial'),
        ('users', '0003_user_access_token_user_code_verifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('town_filter', models.BooleanField(verbose_name='Ограничение по городу')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала')),
                ('users_count', models.IntegerField(default=0, verbose_name='Количество участников')),
                ('users_max_count', models.IntegerField(null=True, verbose_name='Максимальное количество участников')),
                ('telegram_chat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='telegram_chats.telegramchat', verbose_name='Чат в Telegram')),
                ('town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='towns.town', verbose_name='Город')),
                ('user', models.ManyToManyField(related_name='activities', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тренировки',
                'verbose_name_plural': 'Тренировки',
                'db_table': 'activity',
            },
        ),
    ]
