# Generated by Django 5.1.3 on 2024-11-23 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('biscenters', '0001_initial'),
        ('telegram_chats', '0001_initial'),
        ('towns', '0001_initial'),
        ('users', '0003_user_access_token_user_code_verifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='biscenter',
            field=models.ManyToManyField(blank=True, null=True, related_name='activities', to='biscenters.biscenter', verbose_name='Бизнес-центр'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='telegram_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='telegram_chats.telegramchat', verbose_name='Чат в Telegram'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='towns.town', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='activities', to='users.user', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='users_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество участников'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='users_max_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальное количество участников'),
        ),
    ]
