# Generated by Django 5.1.3 on 2024-11-23 16:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0001_initial'),
        ('users', '0003_user_access_token_user_code_verifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FibitLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fibit_logs', to='indicators.indicator', verbose_name='Индикатор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fibit_logs', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог Fibit',
                'verbose_name_plural': 'Логи Fibit',
                'db_table': 'fibit_log',
            },
        ),
    ]
