# Generated by Django 5.1.3 on 2024-11-23 16:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0003_user_access_token_user_code_verifier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_in_events', to='events.event', verbose_name='Командная активность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_in_events', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участники активности',
                'verbose_name_plural': 'Участники активности',
                'db_table': 'user_in_event',
            },
        ),
    ]
