# Generated by Django 5.1.3 on 2024-11-23 13:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biscenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Бизнес-центр',
                'verbose_name_plural': 'Бизнес-центры',
                'db_table': 'biscenters',
            },
        ),
    ]
