# Generated by Django 5.1.3 on 2024-11-23 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('chat_id', models.CharField(max_length=255, verbose_name='ID чата в Telegram')),
            ],
            options={
                'verbose_name': 'Чат в Telegram',
                'verbose_name_plural': 'Чаты в Telegram',
                'db_table': 'telegram_chat',
            },
        ),
    ]
